### ISSUE TITLE
 Error: Not found: 'dart:ui'

### ISSUE THREAD

**Issue by bbookman** [googlecodelabs/photos-sharing#23]
I've tried a dozen StackOverflow solutions and still can't fix this.
After making certain the Flutter and Dart frameworks are correctly set in Android Studio.  And after running Pub get, when I run the code I see this
```
/Users/../flutter/bin/cache/dart-sdk/bin/dart --enable-asserts --enable-vm-service:60098 /Users/../photos-sharing/lib/main.dart
Observatory listening on http://127.0.0.1:60098/HpLS1OpjPk8=/

lib/main.dart: Warning: Interpreting this as package URI, 'package:sharing_codelab/main.dart'.
../flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
../flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../flutter/packages/flutter/lib/src/material/bottom_sheet.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../flutter/packages/flutter/lib/src/material/bottom_sheet_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../flutter/packages/flutter/lib/src/material/button_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../flutter/packages/flutter/lib/src/material/card_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
```

**Comment by jfschmakeit** [comment]
This issue doesn't seem to be specific to the codelab, but to your general Flutter development set up. 

A few things that you may want to check on your end:
* How are you trying to run the codelab? Does it work if you run it from the commandline (instead of through Android Studio)?
* Are you able to run other Flutter projects?
* Does the output of the `flutter doctor` command give you any hints for anything that's misconfigured or not set up correctly?
* Are you selecting the "Flutter" target when running the application? (The Android Studio UI may offer a 'dart' version and a 'flutter' version - that's in the drop down next to the 'run' icon in the toolbar, make sure to select the one with the Flutter icon.) (See this [stackoverflow question](https://stackoverflow.com/questions/53771058/android-studio-gets-error-on-fresh-flutter-app).)
